"""Constants used by the Andor SDK to configure CCD behavior."""

ACQ_MODE_SINGLE = 1
ACQ_MODE_ACCUMULATE = 2
ACQ_MODE_KINETICS = 3
ACQ_MODE_FAST_KINETICS = 4
ACQ_MODE_UNTIL_ABORT = 5
READ_MODE_FVB = 0
READ_MODE_MULTI_TRACK = 1
READ_MODE_RANDOM_TRACK = 2
READ_MODE_SINGLE_TRACK = 3
READ_MODE_IMAGE = 4
COSMIC_RAY_FILTER_OFF = 0
COSMIC_RAY_FILTER_ON = 2
TRIGGER_MODE_INTERNAL = 0
